### ISSUE TITLE
Linux Agent Update Issue

### ISSUE THREAD

**Issue by angeljrgsr** [amidaware/rmmagent#24]
On auto-update, the following is shown in the logs:

time="2022-11-05T19:35:07-04:00" level=info msg="Agent service started"
time="2022-11-05T20:35:00-04:00" level=info msg="Agent updating from 2.4.0 to 2.4.1"
time="2022-11-05T20:35:02-04:00" level=error msg="AgentUpdate() os.Rename(): rename /jKisjKRBDdfleEZalcAkgLMwlnuirFoTMFigmfsp /usr/local/bin/tacticalagent: invalid cross-device link"

cat /etc/os-release output:

NAME="Linux Mint"
VERSION="21 (Vanessa)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21"
VERSION_ID="21"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=vanessa
UBUNTU_CODENAME=jammy

df -Th output:

Filesystem                                       Type   Size  Used Avail Use% Mounted on
tmpfs                                            tmpfs  3.2G  1.5M  3.2G   1% /run
rpool/ROOT/ubuntu_ppgh72                         zfs    209G  9.5G  200G   5% /
tmpfs                                            tmpfs   16G     0   16G   0% /dev/shm
tmpfs                                            tmpfs  5.0M  4.0K  5.0M   1% /run/lock
rpool/USERDATA/oem_jq7qzg                        zfs    200G  128K  200G   1% /home/oem
rpool/ROOT/ubuntu_ppgh72/var/games               zfs    200G  128K  200G   1% /var/games
rpool/ROOT/ubuntu_ppgh72/srv                     zfs    200G  128K  200G   1% /srv
rpool/ROOT/ubuntu_ppgh72/usr/local               zfs    200G  5.7M  200G   1% /usr/local
rpool/ROOT/ubuntu_ppgh72/var/lib                 zfs    202G  2.4G  200G   2% /var/lib
rpool/USERDATA/root_jq7qzg                       zfs    200G  1.3M  200G   1% /root
rpool/ROOT/ubuntu_ppgh72/var/www                 zfs    200G  128K  200G   1% /var/www
rpool/ROOT/ubuntu_ppgh72/var/spool               zfs    200G  128K  200G   1% /var/spool
rpool/ROOT/ubuntu_ppgh72/var/mail                zfs    200G  128K  200G   1% /var/mail
rpool/ROOT/ubuntu_ppgh72/var/log                 zfs    200G   29M  200G   1% /var/log
rpool/ROOT/ubuntu_ppgh72/var/snap                zfs    200G  128K  200G   1% /var/snap
rpool/ROOT/ubuntu_ppgh72/var/lib/AccountsService zfs    200G  128K  200G   1% /var/lib/AccountsService
rpool/ROOT/ubuntu_ppgh72/var/lib/apt             zfs    200G   83M  200G   1% /var/lib/apt
rpool/ROOT/ubuntu_ppgh72/var/lib/NetworkManager  zfs    200G  256K  200G   1% /var/lib/NetworkManager
rpool/ROOT/ubuntu_ppgh72/var/lib/dpkg            zfs    200G   54M  200G   1% /var/lib/dpkg
bpool/BOOT/ubuntu_ppgh72                         zfs    1.8G  500M  1.3G  28% /boot
/dev/sda1                                        vfat   511M   14M  498M   3% /boot/efi
tmpfs                                            tmpfs  3.2G  7.6M  3.2G   1% /run/user/1000

**Comment by wh1te909** [comment]
fix will be in agent v2.4.6 but you'll need to manually update to that version when it's released and after that agent update will work for future agents

**Comment by angeljrgsr** [comment]
Thanks!Angel R. Rojas, Jr.        President & ***@***.***(813) 655-9247 x201So whether you eat or drink or whatever you do, do it all for the glory of God.- 1 Corinthians 10:31Sent from my iPhone... What you see may not be what I meant to type!On Mar 29, 2023, at 1:23 AM, Dan ***@***.***> wrote:﻿
fix will be in agent v2.4.6 but you'll need to manually update to that version when it's released and after that agent update will work for future agents

**Comment by wh1te909** [comment]
just released
