### ISSUE TITLE
Cannot install Linux Agent when using own CA

### ISSUE THREAD

**Issue by robinrosenberger** [amidaware/rmmagent#26]
I'm trying to install the linux agent, using the command line:
`./rmmagent -m install -api=http://api.mylocaldomain.lokal -cert ./MY-CA-CERT.pem -client-id 1 -site-id 1 -auth XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX -nomesh`
It fails, saying:
`Get "https://api.mylocaldomain.lokal/api/v3/installer/": x509: certificate signed by unknown authority`
even though I have provided the CA-cert.
Is this a bug or am I using it wrong?

**Comment by dinger1986** [comment]
Are you using code signing?

**Comment by robinrosenberger** [comment]
No code signing. I also tried with LetsEncrypt, that works fine

**Comment by silversword411** [comment]
Using a .local domain and non-public CA is unsupported because it primarily breaks NATS.
