### ISSUE TITLE
mac meshagent install timeout too short

### ISSUE THREAD

**Issue by cfsnate** [amidaware/rmmagent#28]
Need to test on more machines but it seems like at least on M1 ventura the trmm agent install task that install mesh times out before the installer has finished causing a failure in total installation

Any way to increase timeout?

**Comment by silversword411** [comment]
Mesh isn't working on Ventura atm

**Comment by wh1te909** [comment]
there is an undocumented `--timeout` flag you can pass to the installer, which was not actually being used anywhere. I just added it specifically for the mesh install command, will be in next release. default is 900 seconds, but you can specify something else if you want.
