### ISSUE TITLE
build files missing

### ISSUE THREAD

**Issue by ykuksenko** [amidaware/rmmagent#31]
The `setup.iss` file references files that seem to be outside the repo. Should these be added to the repo?
https://github.com/amidaware/rmmagent/blob/396d7db8353b572d09ed0bde12faa4e04d284ab2/build/setup.iss#L22-L23

The build instructions in the `/README.md` and `/.github/workflows/ci.yml` do not use the `/build/setup.iss` file as far as I can tell. This is likely why this was not apparent.

**Comment by wh1te909** [comment]
these are our company icons and our copyright only. whitelableing feature is being worked on and will be released soon and you'll be able to upload your own icons to compile the agent with.
