### ISSUE TITLE
RMM Service crash on try to auto-update

### ISSUE THREAD

**Issue by JoachimVeulemans** [amidaware/rmmagent#33]
I see that some agents are not online but mesh agent is running on the agent. I think the TacticalRmm service crashes. And the timestamp of the last update corresponds to this log:

time="" level=info msg="Agent updating from 2.4.2 to 2.4.4"
time="" level=error msg="Get \"https://github.com/amidaware/rmmagent/releases/download/v2.4.4/tacticalagent-v2.4.4-windows-amd64.exe\": dial tcp: lookup github.com: getaddrinfow: The requested name is valid, but no data of the requested type was found."

Since it has not internet connection, it can not do the update but it shouldn't crash the service.

I have this issue open on GitHub: [https://github.com/amidaware/tacticalrmm/issues/1228](https://github.com/amidaware/tacticalrmm/issues/1228)
A task to solve this has been created.

The fact that the agent does not auto-update without internet is not so bad but the fact that it may crash the service, is rather inconvenient.

Any ideas on what I can do?

[Creating this issue as recommended on Discord]

**Comment by wh1te909** [comment]
I think I see why its crashing. Got some old code that I need to remove from agent update. Will be in next release.

**Comment by wh1te909** [comment]
fixed in latest release
