### ISSUE TITLE
Windows XP version

### ISSUE THREAD

**Issue by JoachimVeulemans** [amidaware/rmmagent#4]
Hi

Since this project is now converted to GO  and a Linux agent is possible. Would it be possible to compile this for a Windows XP agent? A simple api connection with remote desktop capabilities would be already amazing. In my opinion, it would be nice to have 'a' solution for this, it does not need to include all the features.

I know this isn't easy but I think a lot of systems include older operating systems. A wider OS support would be a requirement for a lot of companies to switch over to Tactical RMM.

Thank you for your time.

**Comment by wh1te909** [comment]
Hi, so golang 1.10 was the last version to support Windows XP so it would not even be possible anymore since the agent is built with golang 1.17, and will be moving to go 1.18 soon to make use of generics. You can try installing golang 1.10 and compiling the agent and see if it runs on XP.
