### ISSUE TITLE
Support driver updates

### ISSUE THREAD

**Issue by MalteKiefer** [amidaware/rmmagent#43]
The Windows Update API supports to search for driver updates:

https://learn.microsoft.com/en-us/windows/win32/api/wuapi/nf-wuapi-iupdatesearcher-search

Can you add this to the update search?
Maybe with a new category, "Drivers"?
Maybe this is helpful:
https://heinz-otto.blogspot.com/2018/10/powershell-und-windows-update.html

**Comment by silversword411** [comment]
Duplicate
https://github.com/amidaware/tacticalrmm/issues/1188
