### ISSUE TITLE
Terminal Server / RDS License 2019 problem

### ISSUE THREAD

**Issue by JeriMind** [amidaware/rmmagent#45]
Hi,

after the Agent (v2.6.2) installation on 2 servers
1 x Windows Server 2019 RDS (Server61)
1 x Windows Server 2019 license service (Server15)

we sporadically get the license problem message in an RDS session (after 60 minutes the connection is disconnected)

the event log on the terminal server says the following:
``
Protocol name: Microsoft-Windows-TerminalServices-RemoteConnectionManager/Admin
Source: Microsoft-Windows-TerminalServices-RemoteConnectionManager
Date: 02/22/2024 16:55:56
Event ID: 50282
Task category: None
Level: Warning
Keywords:
User: Network service
Computer: Server61
Description:
No Remote Desktop license server is specified for the Remote Desktop host server. Use the Remote Desktop Host Configuration Utility to specify a license server for the Remote Desktop host server.
Event XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-TerminalServices-RemoteConnectionManager" Guid="{c76baa63-ae81-421c-b425-340b4b24157f}" />
    <EventID>50282</EventID>
    <Version>0</version>
    <Level>3</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x4000000000000000</Keywords>
    <TimeCreated SystemTime="2024-02-22T15:55:56.026168900Z" />
    <EventRecordID>507</EventRecordID>
    <Correlation />
    <Execution ProcessID="1072" ThreadID="10860" />
    <Channel>Microsoft-Windows-TerminalServices-RemoteConnectionManager/Admin</Channel>
    <Computer>Server61</Computer>
    <Security UserID="S-1-5-20" />
  </System>
  <EventData>
  </EventData>
</Event>
``

But everything is configured and worked fine until Agent installation. 
After uninstallation the Agent from both Server, the message no longer appears. Perhaps something is being blocked?

**Comment by dinger1986** [comment]
Not an issue I have seen and we run a number of RDS servers, @wh1te909 I can get a test server up and running if that helps?

**Comment by JeriMind** [comment]
sorry, it's not the agent. I thought the message had disappeared. But it has just appeared again for another user.

**Comment by dinger1986** [comment]
I thought it was odd it was caused by the agent :), good luck sorting the issue

**Comment by JeriMind** [comment]
I thought so too. Unfortunately not so :( thank you very much
