### ISSUE TITLE
Error Building RMM agent 

### ISSUE THREAD

**Issue by IndianAlu** [amidaware/rmmagent#46]
I'm using Vs code to build the rmmagent using "go build" and it does create rmmagent.exe file in the same directory, but meanwhile if I download tacticalrmmagent.exe from releases of this repo, after execution it does create files in "ProgramFiles"  but while building it locally it doesn't create any file in program files.

*Note: I'm new to development if there is any mistake please guide me.
*- I want to add some additional functionality to the agent, like it shouldn't delete mesh agent if tactical agent is deleted. any many more.

Please help me out.

![1github](https://github.com/amidaware/rmmagent/assets/143686138/749957a5-210b-42c3-ae8b-6b949b301580)

**Comment by dinger1986** [comment]
builds fine for me
