### ISSUE TITLE
Virustotal - Many reports

### ISSUE THREAD

**Issue by pdifeo** [amidaware/rmmagent#53]
Hi, 

I do not remember the list being with many reports. After many months of using the agent, now even Malwarebytes reports it. I point out that only the installer is reported. Is there any vulnerability discovered recently?

https://www.virustotal.com/gui/file/d6c7bdab07151678b713a02efe7ad5281b194b0d5b538061bdafdf2c4ca1fdaa

![image](https://github.com/user-attachments/assets/7a12b498-f480-4516-8bb9-2ea3fac0f20a)

![image](https://github.com/user-attachments/assets/01fecd63-8209-45a1-9090-23bfe08d755e)

**Comment by dinger1986** [comment]
https://docs.tacticalrmm.com/av/#antivirus

**Comment by pdifeo** [comment]
I am familiar with the documentation you point out. My point was a different one. Thank you in any case

**Comment by silversword411** [comment]
There is no known issues, just AV companies doing what AV companies do. It is still a remote access tool that can do anything it's programmed to do to the system.
I'd recommend using it to uninstall malwarebytes and just use the built in Defender which is just as good with none of the performance degredation.
