### ISSUE TITLE
Linux Agent: Reboot Required Logic Wrong

### ISSUE THREAD

**Issue by eCloudJTuttle** [amidaware/rmmagent#8]
For all of our Linux servers, they all show "Reboot Required". Running the command on the machine "needs-restarting" returns code 0, so machine does not require a reboot.

The source code looks for the file needs-restarting and returns true if the file exists. If the file does exist, the command should be called, and if the return code is not zero, then it requires reboot.

**Comment by wh1te909** [comment]
thanks nice catch! I totally did forget to actually call the binary lol
