### ISSUE TITLE
Agent v.2.0.4 - Unable to install agent - Get "https://rmmapi.domain/api/v3/installer/": EOF.

### ISSUE THREAD

**Issue by JoachimVeulemans** [amidaware/rmmagent#9]
I am having the same problem as in #5.
 
The error I am getting is Get "https://rmmapi.domain/api/v3/installer/": EOF.

Output of check_mesh:
![image](https://user-images.githubusercontent.com/32447944/170005187-f01f66f7-da39-4cbe-99e7-6b1bced5a7cc.png)

Output installer:
![image](https://user-images.githubusercontent.com/32447944/170004673-64c01c8d-7dad-42ab-9366-fbdb2d3077d8.png)

Output chrome on agent:
![image](https://user-images.githubusercontent.com/32447944/170005349-94479d2d-791e-4f73-9d16-068dcbe9edfb.png)

**Comment by wh1te909** [comment]
this is not an agent issue and also not a bug, probably something custom to your setup. please open a discussion (not issue) in the main repo and provide a detailed description of your environment and read through the troubleshooting section of the docs and paste all the logs mentioned there
